version: '3.8'

services:

  app:
    build:
      context: .
    container_name: app
    entrypoint: wait-for database:3306 -t 40 -- sh ./start.sh
    volumes:
      - ./src:/usr/src/app
    depends_on:
      - database

  nginx:
    build:
      context: ./nginx
    container_name: nginx
    links:
      - app
    ports:
      - "8080:80"

  database:
    platform: linux/x86_64
    image: mysql:5.7
    restart: always
    tty: true
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=node_db
